#!/usr/bin/env python3
"""Keeps ~/.youtube_cookies.txt genuinely fresh by periodically loading YouTube
in a real, persistent, logged-in Chromium profile via Playwright, then
re-exporting its cookies in Netscape format - the same file
collect_raw_transcripts.py and whisper_transcribe.py already read via --cookies.

Real incident this addresses (2026-08-20): a one-time cookie export (via
`yt-dlp --cookies-from-browser` from Windows Firefox) stopped being accepted
by YouTube's anti-bot check even though the cookies themselves were still
valid session cookies - the suspicion is that yt-dlp's own HTTP/TLS
fingerprint, not the cookie content, is what's flagged. Cookies exported from
an actual live browser session (real TLS fingerprint, real JS execution) and
refreshed periodically should look more like normal traffic than a one-time
static export used indefinitely.

This script does NOT change how videos are downloaded - yt-dlp keeps doing
that exactly as before. It only keeps the cookie file it reads genuinely
current.

Three modes:
  --import-cookies PATH  Real incident 2026-08-20: --seed (below) triggers
            Google's "This browser or app may not be secure" block, because
            Google actively detects Playwright/Selenium-controlled browsers
            during an active SIGN-IN attempt specifically - not just general
            automated browsing. The fix: never attempt to sign in inside
            Playwright at all. Instead, import already-valid cookies exported
            from a real, non-automated browser (the same Netscape-format file
            `.youtube_cookies.txt` already produced via
            `yt-dlp --cookies-from-browser` from Windows Firefox) directly
            into the Playwright persistent context via `context.add_cookies()`.
            No login flow happens inside the automated browser, so Google's
            sign-in-specific automation detection never triggers. This is now
            the PREFERRED way to initialize the profile - try this first.
  --seed    Launch a REAL, visible (non-headless) browser window so a human
            can log into YouTube/Google manually inside Playwright itself.
            Kept as a fallback for if the imported cookies ever fully expire
            and a fresh login is genuinely needed - but expect the same
            Google automation block described above when using it. This step
            cannot be automated by Claude either way - Claude is never
            allowed to enter credentials/passwords, so a person has to do
            this interactively regardless of which mode eventually works.
  --refresh Launch headless using the already-initialized profile, visit
            YouTube briefly (looks like normal browsing, not just a bare API
            hit), export cookies to COOKIES_FILE. Safe to run unattended on a
            schedule once --import-cookies or --seed has been done once.
"""
import argparse
import http.cookiejar
import sys
import time
from pathlib import Path

from playwright.sync_api import sync_playwright

VAULT_ROOT = Path(__file__).resolve().parent.parent
PROFILE_DIR = VAULT_ROOT / ".playwright_profile"
COOKIES_FILE = VAULT_ROOT / ".youtube_cookies.txt"

# Overrides the most obvious automation tell (navigator.webdriver === true,
# set by every real WebDriver-based automation tool including Playwright) on
# every page load in this context. Not a guarantee against detection - Google
# and YouTube both use much deeper fingerprinting than this single flag - but
# a real, well-documented, low-risk reduction in the most naive detection
# signal, worth doing regardless of which cookie-init path is used.
STEALTH_INIT_SCRIPT = "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# This file was generated by playwright_cookie_refresh.py - edits will be lost.\n\n"
)


def _cookies_to_netscape(cookies: list) -> str:
    lines = [NETSCAPE_HEADER]
    for c in cookies:
        domain = c["domain"]
        # yt-dlp/Netscape convention: a leading dot means "include subdomains"
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = str(int(c["expires"])) if c.get("expires", -1) and c["expires"] > 0 else "0"
        name = c["name"]
        value = c["value"]
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def _netscape_to_playwright_cookies(path: Path) -> list:
    """Real Netscape-format parsing via http.cookiejar (stdlib), not a hand-rolled
    line-splitter - this format has edge cases (comment lines, #HttpOnly_ prefix
    some exporters use) that a naive parser would silently mishandle."""
    jar = http.cookiejar.MozillaCookieJar(str(path))
    jar.load(ignore_discard=True, ignore_expires=True)
    out = []
    for c in jar:
        out.append({
            "name": c.name,
            "value": c.value,
            "domain": c.domain,
            "path": c.path,
            "expires": c.expires if c.expires else -1,
            "secure": bool(c.secure),
            "httpOnly": False,  # http.cookiejar doesn't expose this; harmless default for our use
        })
    return out


def import_cookies(source: Path) -> int:
    if not source.exists():
        print(f"Cookie file not found: {source}", file=sys.stderr)
        return 1
    cookies = _netscape_to_playwright_cookies(source)
    yt_cookies = [c for c in cookies if "youtube.com" in c["domain"] or "google.com" in c["domain"]]
    if not yt_cookies:
        print(f"No YouTube/Google cookies found in {source}.", file=sys.stderr)
        return 1

    PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(str(PROFILE_DIR), headless=True)
        context.add_init_script(STEALTH_INIT_SCRIPT)
        context.add_cookies(yt_cookies)
        page = context.new_page()
        page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
        time.sleep(2)
        # Real login check, not just "did add_cookies() not throw" - the avatar
        # button only renders when YouTube's own page actually considers the
        # session authenticated, which is the thing that actually matters here.
        logged_in = page.locator("#avatar-btn, ytd-topbar-menu-button-renderer").count() > 0
        context.close()

    print(f"Imported {len(yt_cookies)} cookies from {source} into the Playwright profile.")
    if logged_in:
        print("Verified: YouTube shows this session as logged in.")
    else:
        print("WARNING: could not confirm a logged-in indicator on youtube.com - "
              "the cookies may be stale/expired, or YouTube's UI changed. "
              "Try a fresh cookie export first, or fall back to --seed.", file=sys.stderr)
    return 0 if logged_in else 1


def seed() -> None:
    PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Launching a visible Chromium window using profile: {PROFILE_DIR}")
    print("NOTE: Google actively detects automated browsers during sign-in and may")
    print("show 'This browser or app may not be secure' - if that happens, cancel")
    print("and use --import-cookies instead (imports your already-logged-in Windows")
    print("browser's cookies without ever attempting a login inside Playwright).")
    print("Log into your Google/YouTube account normally in the window that opens.")
    print("Once you're logged in and can see your account avatar on youtube.com,")
    print("come back here and press Enter to save the session and close the browser.")
    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            str(PROFILE_DIR),
            headless=False,
            viewport={"width": 1280, "height": 900},
        )
        context.add_init_script(STEALTH_INIT_SCRIPT)
        page = context.new_page()
        page.goto("https://www.youtube.com", wait_until="domcontentloaded")
        input("\nPress Enter here once logged in (browser window stays open until then)... ")
        cookies = context.cookies()
        yt_cookies = [c for c in cookies if "youtube.com" in c["domain"] or "google.com" in c["domain"]]
        print(f"Captured {len(yt_cookies)} YouTube/Google cookies.")
        context.close()
    print("Profile saved. Run --refresh anytime from now on (including on a schedule).")


def refresh() -> int:
    if not PROFILE_DIR.exists():
        print("No seeded profile found - run --seed first (needs a real interactive login).", file=sys.stderr)
        return 1
    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            str(PROFILE_DIR),
            headless=True,
        )
        context.add_init_script(STEALTH_INIT_SCRIPT)
        page = context.new_page()
        page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
        # Brief, human-scale dwell + one light interaction rather than an instant
        # bare hit - the goal is cookies attached to traffic that looks like a
        # real visit, not a scripted one-shot fetch.
        time.sleep(3)
        try:
            page.mouse.wheel(0, 400)
            time.sleep(1.5)
        except Exception:
            pass
        cookies = context.cookies()
        yt_cookies = [c for c in cookies if "youtube.com" in c["domain"] or "google.com" in c["domain"]]
        context.close()

    if not yt_cookies:
        print("No cookies captured - profile may not be logged in. Re-run --seed.", file=sys.stderr)
        return 1

    tmp = COOKIES_FILE.with_suffix(COOKIES_FILE.suffix + ".tmp")
    tmp.write_text(_cookies_to_netscape(yt_cookies), encoding="utf-8")
    tmp.replace(COOKIES_FILE)  # atomic - collectors reading this file mid-refresh never see a partial write
    print(f"Refreshed {len(yt_cookies)} cookies -> {COOKIES_FILE}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--import-cookies", metavar="PATH", type=Path,
                         help="preferred: initialize the profile from an existing Netscape cookie file "
                              "(e.g. the vault's own .youtube_cookies.txt) - no login attempt inside "
                              "Playwright, avoids Google's automation-login block entirely")
    parser.add_argument("--seed", action="store_true",
                         help="fallback: one-time interactive login inside Playwright - may trigger "
                              "Google's automation detection, try --import-cookies first")
    parser.add_argument("--refresh", action="store_true", help="headless cookie re-export (safe to schedule)")
    args = parser.parse_args()

    if args.import_cookies:
        return import_cookies(args.import_cookies)
    if args.seed:
        seed()
        return 0
    if args.refresh:
        return refresh()
    parser.error("specify --import-cookies PATH (preferred), --seed (fallback, interactive), or --refresh (scheduled)")


if __name__ == "__main__":
    sys.exit(main())
